// Curated Flickr tag lists per territory, following the original Mexican model:
// territory name + local-language variants + most-photographed cities.
// Tags are comma-separated (Flickr ORs them) and URLSearchParams handles encoding.
// The first territory of each country is its default selection.

export const countries = [
  {
    label: "Mexico",
    territories: [
      { value: "querétaro,queretaro", label: "Querétaro" },
      { value: "ciudaddeméxico,iztapalapa", label: "Ciudad de México" },
      { value: "aguascalientes", label: "Aguascalientes" },
      { value: "bajacalifornia", label: "Baja California" },
      { value: "campeche", label: "Campeche" },
      { value: "chiapas", label: "Chiapas" },
      { value: "Saltillo", label: "Saltillo" },
      { value: "Colima,manzanillo", label: "Colima" },
      { value: "Durango", label: "Durango" },
      { value: "Guanajuato", label: "Guanajuato" },
      { value: "Guerrero", label: "Guerrero" },
      { value: "Hidalgo", label: "Hidalgo" },
      { value: "Jalisco,Guadalajara", label: "Guadalajara" },
      {
        value: "estadodemexico,ecatepec,tolucadelerdo",
        label: "Estado De México",
      },
      { value: "michoacán,michoacan,morelia", label: "Michoacán" },
      { value: "morelos,cuernavaca", label: "Morelos" },
      { value: "nayarit,tepic", label: "Nayarit" },
      { value: "monterrey,nuevoleon", label: "Monterrey" },
      { value: "oaxaca", label: "Oaxaca" },
      { value: "puebla,puebladezaragoza", label: "Puebla" },
      { value: "quintanaroo,chetumal,cancún,cancun", label: "Quintana Roo" },
      { value: "sanluispotosi,sanluispotosí", label: "San Luis Potosí" },
      { value: "sinaloa,culiacán,culiacan", label: "Sinaloa" },
      { value: "sonora,hermosillo", label: "Sonora" },
      { value: "tabasco,villahermosa", label: "Tabasco" },
      { value: "tamaulipas,ciudadvictoria,reynosa", label: "Tamaulipas" },
      {
        value: "tlaxcala,tlaxcaladexicohténcatl,xicohténcatl,xicotencatl",
        label: "Tlaxcala",
      },
      { value: "veracruz", label: "Veracruz" },
      { value: "yucatán,yucatan,mérida,merida", label: "Yucatán" },
      { value: "zacatecas", label: "Zacatecas" },
    ],
  },
  {
    label: "France",
    territories: [
      { value: "îledefrance,iledefrance,paris", label: "Île-de-France" },
      {
        value: "rhônealpes,rhonealpes,lyon,auvergne",
        label: "Auvergne-Rhône-Alpes",
      },
      {
        value: "bourgogne,burgundy,dijon,franchecomté,franchecomte",
        label: "Bourgogne-Franche-Comté",
      },
      { value: "bretagne,brittany,rennes", label: "Brittany" },
      {
        value: "valdeloire,loirevalley,tours,orléans,orleans",
        label: "Centre-Val de Loire",
      },
      { value: "corse,corsica,ajaccio", label: "Corsica" },
      { value: "alsace,strasbourg,lorraine", label: "Grand Est" },
      {
        value: "hautsdefrance,lille,picardie,nordpasdecalais",
        label: "Hauts-de-France",
      },
      { value: "normandie,normandy,rouen", label: "Normandy" },
      { value: "aquitaine,bordeaux", label: "Nouvelle-Aquitaine" },
      { value: "occitanie,toulouse,montpellier,languedoc", label: "Occitanie" },
      { value: "paysdelaloire,nantes", label: "Pays de la Loire" },
      {
        value: "provence,marseille,nice,côtedazur,cotedazur",
        label: "Provence-Alpes-Côte d'Azur",
      },
    ],
  },
  {
    label: "Germany",
    territories: [
      { value: "berlin", label: "Berlin" },
      {
        value: "badenwürttemberg,badenwurttemberg,stuttgart,heidelberg",
        label: "Baden-Württemberg",
      },
      {
        value: "bayern,bavaria,münchen,munich,nürnberg,nuremberg",
        label: "Bavaria",
      },
      { value: "brandenburg,potsdam", label: "Brandenburg" },
      { value: "bremen", label: "Bremen" },
      { value: "hamburg", label: "Hamburg" },
      { value: "hessen,hesse,frankfurt", label: "Hesse" },
      {
        value: "niedersachsen,lowersaxony,hannover,hanover",
        label: "Lower Saxony",
      },
      {
        value: "mecklenburgvorpommern,rostock",
        label: "Mecklenburg-Vorpommern",
      },
      {
        value: "nordrheinwestfalen,köln,cologne,düsseldorf,dusseldorf,dortmund",
        label: "North Rhine-Westphalia",
      },
      { value: "rheinlandpfalz,mainz", label: "Rhineland-Palatinate" },
      { value: "saarland,saarbrücken,saarbrucken", label: "Saarland" },
      { value: "sachsen,saxony,dresden,leipzig", label: "Saxony" },
      { value: "sachsenanhalt,magdeburg", label: "Saxony-Anhalt" },
      {
        value: "schleswigholstein,kiel,lübeck,lubeck",
        label: "Schleswig-Holstein",
      },
      { value: "thüringen,thuringia,erfurt,weimar", label: "Thuringia" },
    ],
  },
  {
    label: "Japan",
    territories: [
      { value: "tokyo,東京", label: "Tokyo" },
      { value: "aichi,愛知,nagoya,名古屋", label: "Aichi" },
      { value: "akita,秋田", label: "Akita" },
      { value: "aomori,青森", label: "Aomori" },
      { value: "chiba,千葉", label: "Chiba" },
      { value: "ehime,愛媛,matsuyama", label: "Ehime" },
      { value: "fukui,福井", label: "Fukui" },
      { value: "fukuoka,福岡", label: "Fukuoka" },
      { value: "fukushima,福島", label: "Fukushima" },
      { value: "gifu,岐阜,takayama", label: "Gifu" },
      { value: "gunma,群馬", label: "Gunma" },
      { value: "hiroshima,広島", label: "Hiroshima" },
      { value: "hokkaido,北海道,sapporo,札幌", label: "Hokkaido" },
      { value: "hyogo,兵庫,kobe,神戸", label: "Hyogo" },
      { value: "ibaraki,茨城", label: "Ibaraki" },
      { value: "ishikawa,石川,kanazawa,金沢", label: "Ishikawa" },
      { value: "iwate,岩手", label: "Iwate" },
      { value: "kagawa,香川", label: "Kagawa" },
      { value: "kagoshima,鹿児島", label: "Kagoshima" },
      { value: "kanagawa,神奈川,yokohama,横浜,kamakura", label: "Kanagawa" },
      { value: "kochi,高知", label: "Kochi" },
      { value: "kumamoto,熊本", label: "Kumamoto" },
      { value: "kyoto,京都", label: "Kyoto" },
      { value: "mie,三重", label: "Mie" },
      { value: "miyagi,宮城,sendai,仙台", label: "Miyagi" },
      { value: "miyazaki,宮崎", label: "Miyazaki" },
      { value: "nagano,長野", label: "Nagano" },
      { value: "nagasaki,長崎", label: "Nagasaki" },
      { value: "nara,奈良", label: "Nara" },
      { value: "niigata,新潟", label: "Niigata" },
      { value: "oita,大分", label: "Oita" },
      { value: "okayama,岡山", label: "Okayama" },
      { value: "okinawa,沖縄,naha", label: "Okinawa" },
      { value: "osaka,大阪", label: "Osaka" },
      { value: "saga,佐賀", label: "Saga" },
      { value: "saitama,埼玉", label: "Saitama" },
      { value: "shiga,滋賀", label: "Shiga" },
      { value: "shimane,島根", label: "Shimane" },
      { value: "shizuoka,静岡", label: "Shizuoka" },
      { value: "tochigi,栃木,nikko,日光", label: "Tochigi" },
      { value: "tokushima,徳島", label: "Tokushima" },
      { value: "tottori,鳥取", label: "Tottori" },
      { value: "toyama,富山", label: "Toyama" },
      { value: "wakayama,和歌山", label: "Wakayama" },
      { value: "yamagata,山形", label: "Yamagata" },
      { value: "yamaguchi,山口", label: "Yamaguchi" },
      { value: "yamanashi,山梨", label: "Yamanashi" },
    ],
  },
  {
    label: "United Kingdom",
    territories: [
      { value: "london", label: "London" },
      { value: "england,manchester,liverpool,birmingham", label: "England" },
      { value: "northernireland,belfast", label: "Northern Ireland" },
      { value: "scotland,edinburgh,glasgow,highlands", label: "Scotland" },
      { value: "wales,cymru,cardiff", label: "Wales" },
    ],
  },
  {
    label: "United States",
    territories: [
      { value: "newyork,newyorkcity,nyc,brooklyn", label: "New York" },
      { value: "alabama", label: "Alabama" },
      { value: "alaska,anchorage", label: "Alaska" },
      { value: "arizona,phoenix,tucson", label: "Arizona" },
      { value: "arkansas,littlerock", label: "Arkansas" },
      {
        value: "california,losangeles,sanfrancisco,sandiego",
        label: "California",
      },
      { value: "colorado,denver", label: "Colorado" },
      { value: "connecticut,hartford", label: "Connecticut" },
      { value: "delaware", label: "Delaware" },
      { value: "florida,miami,orlando", label: "Florida" },
      { value: "georgia,atlanta,savannah", label: "Georgia" },
      { value: "hawaii,honolulu", label: "Hawaii" },
      { value: "idaho,boise", label: "Idaho" },
      { value: "illinois,chicago", label: "Illinois" },
      { value: "indiana,indianapolis", label: "Indiana" },
      { value: "iowa,desmoines", label: "Iowa" },
      { value: "kansas,wichita", label: "Kansas" },
      { value: "kentucky,louisville,lexington", label: "Kentucky" },
      { value: "louisiana,neworleans", label: "Louisiana" },
      { value: "maine", label: "Maine" },
      { value: "maryland,baltimore", label: "Maryland" },
      { value: "massachusetts,boston", label: "Massachusetts" },
      { value: "michigan,detroit", label: "Michigan" },
      { value: "minnesota,minneapolis", label: "Minnesota" },
      { value: "mississippi", label: "Mississippi" },
      { value: "missouri,stlouis,kansascity", label: "Missouri" },
      { value: "montana", label: "Montana" },
      { value: "nebraska,omaha", label: "Nebraska" },
      { value: "nevada,lasvegas,reno", label: "Nevada" },
      { value: "newhampshire", label: "New Hampshire" },
      { value: "newjersey", label: "New Jersey" },
      { value: "newmexico,albuquerque,santafe", label: "New Mexico" },
      { value: "northcarolina,charlotte,raleigh", label: "North Carolina" },
      { value: "northdakota,fargo", label: "North Dakota" },
      { value: "ohio,cleveland,columbus,cincinnati", label: "Ohio" },
      { value: "oklahoma,oklahomacity,tulsa", label: "Oklahoma" },
      { value: "oregon,portland", label: "Oregon" },
      { value: "pennsylvania,philadelphia,pittsburgh", label: "Pennsylvania" },
      { value: "rhodeisland,providence", label: "Rhode Island" },
      { value: "southcarolina,charleston", label: "South Carolina" },
      { value: "southdakota", label: "South Dakota" },
      { value: "tennessee,nashville,memphis", label: "Tennessee" },
      { value: "texas,houston,austin,dallas,sanantonio", label: "Texas" },
      { value: "utah,saltlakecity", label: "Utah" },
      { value: "vermont", label: "Vermont" },
      { value: "virginia,richmond", label: "Virginia" },
      { value: "washingtonstate,washington,seattle", label: "Washington" },
      { value: "washingtondc,districtofcolumbia", label: "Washington, D.C." },
      { value: "westvirginia", label: "West Virginia" },
      { value: "wisconsin,milwaukee,madison", label: "Wisconsin" },
      { value: "wyoming,yellowstone", label: "Wyoming" },
    ],
  },
];
